---
- name: Setup frontend server
  become: yes
  hosts: frontend
  vars:
    backend_ip: "{{ hostvars[groups['backend'][0]].inventory_hostname }}"
  tasks:
    - name: Install dependencies
      yum:
        name: nginx
        state: present
        update_cache: yes

    - name: create nginx conf for proxy to backend
      copy:
        dest: /etc/nginx/conf.d/frontend.conf
        content: |
          server {
              listen 80;
              server_name _;

              location / {
                  proxy_pass http://{{ backend_ip }}:8080;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }
        owner: root
        group: root
        mode: '0644'

    - name: test nginx configuration  
      command: nginx -t
      register: nginx_test
      failed_when: "'successful' not in (nginx_test.stdout + nginx_test.stderr)"   

    - name: Reload nginx
      service:
        name: nginx
        state: restarted
        enabled: yes
